import * as Clipboard from "expo-clipboard";

import type { AgentOutput } from "./pdf";

export async function copyText(text: string): Promise<boolean> {
  try {
    await Clipboard.setStringAsync(text);
    return true;
  } catch {
    return false;
  }
}

export interface FullReportArgs {
  local: string;
  employer: string;
  role: string;
  problem: string;
  agentOutputs: AgentOutput[];
  finalMarkdown: string;
}

export function buildFullReportText(args: FullReportArgs): string {
  const date = new Date().toLocaleString("en-CA");
  const lines: string[] = [];

  lines.push("WORKERSHIELD REPORT");
  lines.push("CONFIDENTIAL — UNION DOCUMENT");
  lines.push(`Generated: ${date}`);
  lines.push("");
  lines.push(`Local: ${args.local}`);
  lines.push(`Employer: ${args.employer}`);
  lines.push(`Role: ${args.role}`);
  lines.push("");
  lines.push("PROBLEM:");
  lines.push(args.problem);
  lines.push("");

  for (const a of args.agentOutputs) {
    if (!a.output?.trim()) continue;
    lines.push(`${"=".repeat(50)}`);
    lines.push(`AGENT: ${a.label.toUpperCase()}`);
    lines.push(`${"=".repeat(50)}`);
    lines.push(a.output.trim());
    lines.push("");
  }

  lines.push(`${"=".repeat(50)}`);
  lines.push("★ WORKERSHIELD FINAL RESPONSE");
  lines.push(`${"=".repeat(50)}`);
  lines.push(args.finalMarkdown.trim());
  lines.push("");
  lines.push("---");
  lines.push(
    "Generated by WorkerShield — Confidential Union Document",
  );

  return lines.join("\n");
}

export async function copyFullReport(args: FullReportArgs): Promise<boolean> {
  const text = buildFullReportText(args);
  return copyText(text);
}
