kind = "mobile"
previewPath = "/"
title = "WorkerShield"
version = "1.0.0"
id = "artifacts/workershield"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24384

[services.development]
run = "pnpm --filter @workspace/workershield run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/workershield", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/workershield", "run", "serve" ]

[services.env]
PORT = "24384"
BASE_PATH = "/"
